### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by SchoolofCommons** [cubeca/cube#408]
### Your public repo

https://github.com/schoolofcommons/gov4git-identity-public.git

### Your public branch

main

**Comment by SchoolofCommons** [comment]
approve

**Comment by AshBC** [comment]
approve

**Comment by AshBC** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 25-Sep-24 19:17:36 UTC` by Gov4Git `dev`

@schoolofcommons was added to the community.
