### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by petar** [cubeca/cube#410]
### Your public repo

https://github.com/petar/gov4git-identity-public.git

### Your public branch

main

**Comment by AshBC** [comment]
approve

**Comment by AshBC** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 01-Oct-24 20:28:10 UTC` by Gov4Git `dev`

@petar was added to the community.
