### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by gabrielhensche** [cubeca/cube#434]
### Your public repo

https://github.com/gabrielhensche/gov4git-identity-public.git

### Your public branch

main

**Comment by AshBC** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Friday, 29-Nov-24 15:57:08 UTC` by Gov4Git `dev`

@gabrielhensche was added to the community.
